version: '3.3'
services:
### MySQL Container
  mysql:
    env_file: ./.env
    build:
      context:    .
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE      =${MYSQL_DATABASE}
        - MYSQL_USER          =${MYSQL_USER}
        - MYSQL_PASSWORD      =${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD =${MYSQL_ROOT_PASSWORD}
        - MYSQL_PORT          =${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:3306"

