version: '3.3'
services:
### MySQL Container
  mysql_master:
    env_file: ./.env
    build:
      context:    .
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_MASTER_DATABASE}
        - MYSQL_USER=${MYSQL_MASTER_USER}
        - MYSQL_PASSWORD=${MYSQL_MASTER_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_MASTER_ROOT_PASSWORD}
        - MYSQL_PORT=${MYSQL_MASTER_PORT}
    ports:
      - "${MYSQL_MASTER_PORT}:3306"

  mysql_slave_1:
    env_file: ./.env
    build:
      context:    .
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_SLAVE_1_DATABASE}
        - MYSQL_USER=${MYSQL_SLAVE_1_USER}
        - MYSQL_PASSWORD=${MYSQL_SLAVE_1_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_SLAVE_1_ROOT_PASSWORD}
        - MYSQL_PORT=${MYSQL_SLAVE_1_PORT}
    ports:
      - "${MYSQL_SLAVE_1_PORT}:3307"
  
  mysql_slave_2:
    env_file: ./.env
    build:
      context:    .
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_SLAVE_2_DATABASE}
        - MYSQL_USER=${MYSQL_SLAVE_2_USER}
        - MYSQL_PASSWORD=${MYSQL_SLAVE_2_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_SLAVE_2_ROOT_PASSWORD}
        - MYSQL_PORT=${MYSQL_SLAVE_2_PORT}
    ports:
      - "${MYSQL_SLAVE_2_PORT}:3308"